In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv("covid_toy.csv")

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size = 0.2)

In [7]:
X_train

    age  gender  fever   cough       city
71   75  Female  104.0  Strong      Delhi
82   24    Male   98.0    Mild    Kolkata
80   14  Female   99.0    Mild     Mumbai
68   54  Female  104.0  Strong    Kolkata
85   16  Female  103.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
7    20  Female    NaN  Strong     Mumbai
91   38    Male    NaN    Mild      Delhi
4    65  Female  101.0    Mild     Mumbai
59    6  Female  104.0    Mild    Kolkata
61   81  Female   98.0  Strong     Mumbai

[80 rows x 5 columns]

In [8]:
from sklearn.compose import ColumnTransformer

In [13]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [14]:
transformer.fit_transform(X_train).shape

NameError: name 'transformer' is not defined