Day-16

In [1]:
import pandas as pd

Working with JSON (JavaScript Object Notation)

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,0.0384
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,0.6840
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,0.8380
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,3.8200
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,2.4800
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,0.1690
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,0.1970
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,0.2790
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-18,1787011201,0.2790

Working with SQL

In [4]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 15.0 MB/s eta 0:00:01
     ---- ----------------------------------- 1.3/11.9 MB 4.1 MB/s eta 0:00:03
     ------ --------------------------------- 1.8/11.9 MB 4.2 MB/s eta 0:00:03
     ------- -------------------------------- 2.1/11.9 MB 3.6 MB/s eta 0:00:03
     -------- ------------------------------- 2.6/11.9 MB 2.7 MB/s eta 0:00:04
     --------- ------------------------------ 2.9/11.9 MB 2.6 MB/s eta 0:00:04
     ----------- ---------------------------- 3.4/11.9 MB 2.5 MB/s eta 0:00:04
     ----------- ---------------------------- 3.4/11.9 MB 2.5 MB/s eta 0:00:04
     ------------ --------------------------- 3.7/11.9 MB 2.1 MB/s eta 0:00:04
     ------------- -------------------------- 3.9/11.9 MB 2.1 MB/s eta 0:00:04
     --------------- ------------------------ 4.5/11.9 MB 2.0 MB/s eta 0:00:04
     ----------------- ---------------------- 5.2/11.9 MB 2.1 MB/s eta 0:00:04
     -------------------- ------------------- 6.0/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 2.4 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 2.6 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 2.7 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 2.7 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 2.6 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 2.7 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.8 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.7 MB/s  0:00:04
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=8e334f4d4cedba400022a4e09f5b52cfc4252a135eb0240f37c1c3b72bca13af
  Stored in directory: c:\users\souma\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souma\anaconda5\Lib\anaconda6\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souma\anaconda5\Lib\anaconda6\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souma\anaconda5\Lib\anaconda6\Lib\site-packages)

In [5]:
import mysql.connector

In [10]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\souma\anaconda5\lib\anaconda6\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\souma\anaconda5\lib\anaconda6\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\souma\anaconda5\lib\anaconda6\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souma\anaconda5\Lib\anaconda6\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souma\anaconda5\Lib\anaconda6\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\souma\anaconda5\Lib\anaconda6\Lib\site-packages)

In [13]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:@localhost:3306/world"
)

df = pd.read_sql_query(
    "SELECT * FROM countrylanguage",
    engine
)

print(df.head())

  CountryCode    Language IsOfficial  Percentage
0         ABW       Dutch          T         5.3
1         ABW     English          F         9.5
2         ABW  Papiamento          F        76.7
3         ABW     Spanish          F         7.4
4         AFG     Balochi          F         0.9

In [14]:
df.shape

(984, 4)